domain_path: C:\Users\cenk.keskin\Desktop\Microblaze_Peripheral\Microblaze\export\Microblaze\sw\standalone_microblaze_0
app_src_dir: /tools/Xilinx/2025.1/Vitis/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
